exclude: "build|stubs"

default_language_version:
  python: python3

repos:
  # These are hooks applied to all kinds of different file-types
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
      - id: check-json
        # Exclude vscode-specific json-files. Those can contain comments (//), which are not json
        # standard.
        exclude: '.vscode/(launch|settings|tasks).json'
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--credentials-file=.env", "--allow-missing-credentials"]
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-byte-order-marker
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=2048"]
      - id: end-of-file-fixer

  # Hooks specific for python script-files (.py)
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/autoflake
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/flake8
        language: system
        types: [python]

  # Hooks specific for jupyter notebooks (.ipynb)
  - repo: local
    hooks:
      - id: nbstripout
        name: 'remove outputs from jupyter notebooks (nbstripout)'
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/nbstripout
        language: system
        types: [jupyter]
      - id: nbqa-isort
        name: nb-isort
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/nbqa isort
        language: system
        types: [jupyter]
      - id: nbqa-black
        name: nb-black
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/nbqa black
        language: system
        types: [jupyter]
      - id: nbqa-flake8
        name: nb-flake8
        entry: /Users/bach/.miniconda3/envs/nlp-course/bin/nbqa flake8
        language: system
        types: [jupyter]
